### PR TITLE
Jan

### PR DESCRIPTION
**Pull request by jtroo**

### CODE REVIEW

**Comment by 0spooky2me** [comment]
Can you cherrypick the commits with actual changes?  If we don't want to clutter our workspace, we don't need commits that are already committed.

**Comment by 0spooky2me** [comment]
How much do we care about tab usage/trailing whitespace?  Root readme.md is an older version as well; names are missing.

**Comment by jtroo** [comment]
I say tabs should be tab characters - proper C style, plus good editors can resize a tab to whatever size you want.
Trailing whitespace, idk. Better to remove it I suppose, not sure if worth enforcing

**Comment by 0spooky2me** [comment]
As far as I'm concerned, neither are an issue as long as the code is readable and maintainable.  I prefer to avoid any tab usage, but it's not a big deal.  Trailing whitespace barely makes any difference for us.  Just wanted to know your preference.  This looks good otherwise.

**Comment by jtroo** [comment]
Sure. As long as tabbing is consistent and readable in a given file, it's fine.

**Pull request merged**
